### ISSUE TITLE
[Bug] Delete the content of textbox without checking validation.

### ISSUE THREAD

**Issue by HTTPThanhLuan** [Blazored/FluentValidation#123] opened 2022-03-22 21:48 UTC
https://blazored.github.io/FluentValidation/

There is no validation. If I delete the content of textbox of nested type (for example: Address: Line 1)

**Comment by Sharaf-Mansour** [comment] 2022-03-29 23:14
I Talked about this in #104 and Downgrading to version 2.0.1 Fixes the problem

**Comment by chrissainty** [comment] 2022-05-09 12:38
I'm closing this as a duplicate of #104

**Closed by chrissainty** 2022-05-09 12:38 UTC
Labels: Bug, Triage
